# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('year', models.IntegerField(null=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_directed', to='movies.Person')),
                ('screenplay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_screenpl', to='movies.Person')),
            ],
        ),
        migrations.CreateModel(
            name='StarringPersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128, null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Movie')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(related_name='movies_starr', through='movies.StarringPersons', to='movies.Person'),
        ),
    ]
